### ISSUE TITLE
병렬 연습

### ISSUE THREAD

**Issue by yeongsunpark** [yeongsunpark/cute#4]

**Comment by yeongsunpark** [comment]
Traceback (most recent call last):
  File "/usr/lib64/python3.4/multiprocessing/queues.py", line 247, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/usr/lib64/python3.4/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot serialize '_io.TextIOWrapper' object

위와 같은 오류 생김 ...

**Comment by yeongsunpark** [comment]
한 줄로 되어 있던 코드를 쪼개서 함수로 만들면 더 빨라짐 !!!

**Comment by yeongsunpark** [comment]
with open("select3.txt", "r") as f:
            lenf = f.readlines()
            lenf = tuple(lenf)
            print (len(lenf))
            # self.comp(lenf, 0, r)
            with concurrent.futures.ProcessPoolExecutor(max_workers=workers) as exe:
                fs = {exe.submit(self.comp, lenf, n, r) for n in range(0, len(lenf), r)}

self.comp(lenf,0,r) 이 부분만 그냥 실행하면 잘 되는데 저렇게 병렬하면 안됨. 
타입이 문제인 가 싶어서 리스트를 튜플로도 바꿔보았는데 똑같은 오류 생김.

**Comment by yeongsunpark** [comment]
class 안에 def 들을 적었는데
class 없애고 def 들 독립적으로 하니 코드가 돌아가기는 함. 근데 빨라지는 거 같지는 않는 느낌.

**Comment by yeongsunpark** [comment]
sams/check_dupl.py : 함수 같은 거 없이 한 줄로 쭉 되어 있는 코드. 
sams/check_dupl_def.py : 함수를 쓰긴 썼는데 느림 ㅋㅋㅋ
sams/check_dupl_def2.py : 함수만 쓰고 싶으면 이거 써야함. 
sams/check_dupl_conc.py : class 안에 def 들이 전부 있어서 안 됨. 
sams/check_dupl_conc2.py : 이거 사용함
